name: opencloud

x-daemonless:
  title: "OpenCloud"
  icon: ":material-apps:"  # https://pictogrammers.com/library/mdi/ (material-) or https://simpleicons.org/ (simple-)
  category: "Utilities"
  description: "OpenCloud is a modern file-sync and share platform."
  upstream_url: "https://github.com/daemonless/opencloud"
  web_url: "https://opencloud.eu/"
  user: "bsd"
  mlock: false
  community: "Discord:https://discord.gg/Kb9tkhecZT"
  appjail: true

  docs:
    env:
      PUID: "User ID for the application process"
      PGID: "Group ID for the application process"
      TZ: "Timezone for the container"
      OC_URL: "URL where OpenCloud can be accessed"
    volumes:
      /config: "Configuration directory"
    ports:
      9200: "Web UI"

  notes: |
    !!! warning "Work in Progress"
      This image is functional but may change significantly in a future release.

    ## Breaking changes
    - 

    ## Upgrade from 6.2.0 to 7.0.0
    The upgrade requires a change to the configuration of the "sharing" service. Please follow the steps outlined in the [Upgrade Guide](https://docs.opencloud.eu/docs/admin/maintenance/upgrade/upgrade-guide#verify-configuration-changes) to achieve that.

    ## First run
    OpenCloud generates a default config with insecure settings (not TLS validation) on first start
    or if the `/config/.opencloud` directory does not exist.  
    
    You can define the inital password for the `admin` user by setting the environment variable `IDM_ADMIN_PASSWORD` like this:
    ```yaml
    services:
      opencloud:
        environment:
          - IDM_ADMIN_PASSWORD=<your_admin_password>
    ```

    If you do not set the password with the variable above, OpenCloud generates a random password for the `admin` user and
    you can find it in the logs or in the file `/config/.opencloud/config/opencloud.yaml`.

    ## Remarks
    So far I have only tested this image with `bridge` networking.  
    You may need to add an `extra_host` to your compose file to allow opencloud to connect to it's internal IDP.
    That is at least what I had to do.
    ```yaml
    services:
      opencloud:
        extra_hosts:
          - "host-hostname:127.0.0.1"
    ```
    ## Additional environment variables
    To configure OpenCloud further, you can check out the list of [environment variables](https://docs.opencloud.eu/docs/next/dev/server/services/web/environment-variables).

services:
  opencloud:
    image: ghcr.io/daemonless/opencloud:latest
    container_name: opencloud
    restart: unless-stopped


    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - OC_URL=https://hostname:9200
    extra_hosts:
       - "hostname:127.0.0.1"

    volumes:
      - /path/to/containers/opencloud:/config

    ports:
      - 9200:9200
