#!/bin/sh
# Move the config and data from the old default location
# directly into /config

# Ensure directories exist and have correct ownership
mkdir -p /config
chown -R bsd:bsd /config

if [ ! -d /config/.opencloud ]; then
  # If the old base directory does not exist, we do not do anything
  exit 0
fi

# Generate default config if missing
if [ ! -d /config/config ]; then
  mv /config/.opencloud/* /config
  if [ "$?" -eq 0 ]; then
    rm -r /config/.opencloud
  fi
  echo "[move-config] OpenCloud config and data moved from /config/.opencloud to /config"
fi

